version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgresTasksApp
    ports:
      - '5432:5432'
    volumes:
      - tasksAppVol:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  tasksAppVol:


